/** @typedef {import('./globalOptions').Preset} Preset */

module.exports = {
  chalk: require('chalk').default,
  ...require('./configFiles'),
  ...require('./debug'),
  ...require('./deps'),
  ...require('./env'),
  ...require('./files'),
  ...require('./fn'),
  ...require('./git'),
  ...require('./globalOptions'),
  ...require('./hookable'),
  ...require('./json'),
  ...require('./logger'),
  ...require('./object'),
  ...require('./openBrowser'),
  ...require('./pkg'),
  ...require('./plugin'),
  ...require('./rcPath'),
  ...require('./request'),
  ...require('./run'),
  shouldUseTaobao: require('./shouldUseTaobao'),
  ...require('./spinner'),
  ...require('./terminate'),
  ...require('./validate'),
}
