module.exports = {
  chalk: require('chalk').default,
  ...require('./debug'),
  ...require('./deps'),
  ...require('./env'),
  ...require('./files'),
  ...require('./global-options'),
  ...require('./logger'),
  ...require('./module'),
  ...require('./object'),
  ...require('./openBrowser'),
  ...require('./plugin'),
  ...require('./request'),
  shouldUseTaobao: require('./shouldUseTaobao'),
  ...require('./spinner'),
  ...require('./validate'),
}
